### ISSUE TITLE
social_user is not defined 

### ISSUE THREAD

**Issue by dfrojas** [pythonforfacebook/facebook-sdk#193]
Hi, im trying to post  a message in the wall but i get:

global name 'social_user' is not defined

my code:

def publicar(request):
	graph = facebook.GraphAPI(social_user.extra_data['access_token'])
	graph.put_object('me', 'feed', message='mensaje', link="http://www.test1.com",picture='http://www.thefamilyfocus.ca/images/Inserts/Calendar.png')
	return HttpResponse("hello!")

Im coding with python 2.7

**Comment by martey** [comment]
It looks like you might be using python-social-auth to get an access token, but you never set `social_user` in the `publicar` method. See [this StackOverflow answer](http://stackoverflow.com/a/22790358/113527) for more details.

Since this isn't a bug in the library, but rather a question about how to use it, it would be better suited for the [Google discussion group](https://groups.google.com/forum/#!forum/pythonforfacebook).
