### ISSUE TITLE
Last PyPI version is 2.5 years old

### ISSUE THREAD

**Issue by homm** [pythonforfacebook/facebook-sdk#203]
https://pypi.python.org/pypi/facebook-sdk

**Comment by martey** [comment]
There has been repeated discussion both [on the Google Group](https://groups.google.com/forum/#!topic/pythonforfacebook/Xxj1u22yNXU) and in other issues (see #135 and #157) as to why this is the case.

Because of this, I am closing and locking this issue. If you have concerns or thoughts that have not been previously raised, please start a new thread on the Google Group.
