### ISSUE TITLE
Update Developer Information - Dead Link

### ISSUE THREAD

**Issue by tekNorah** [pythonforfacebook/facebook-sdk#205]
The home page in the developer information section of the PyPi page for this package is pointing to the old repo.

https://pypi.python.org/pypi/facebook-sdk

**Comment by martey** [comment]
I am not sure that this is pointing at the wrong repo, so I am closing this issue.

**Comment by martey** [comment]
More importantly, I assume that once I update the main repository, this problem will go away.

**Comment by martey** [comment]
I think I was confused because of the mention of "the old repo". `martey/facebook-sdk` was a temporary repository created when `pythonforfacebook/facebook-sdk` was accidentally deleted: https://groups.google.com/forum/#!topic/pythonforfacebook/nVKVvX96uhw

I had manually updated the repository on PyPi, but forgot to change it back. Thanks for letting me know about this!

**Comment by tekNorah** [comment]
You are more than welcome!
