### ISSUE TITLE
Update pypi package 

### ISSUE THREAD

**Issue by kbytesys** [pythonforfacebook/facebook-sdk#251]
According to the pypi repository the lastest release is 0.4.0.

I'm trying to use this lib in production with python 3.x and I would like to keep my venvs updated with pip instead of execute some manual upgrades from github/code.

Please, could you update the package with a newer release? It least 3 years since the last update.

**Comment by martey** [comment]
See #192 and https://groups.google.com/forum/#!topic/pythonforfacebook/Xxj1u22yNXU.

**Comment by kbytesys** [comment]
Please reopen this issue.

I really don't understand why you don't want to create a new package release. Using the git source with pip is unreliable and totally broke the dependecy system: many deploy systems rely to requirements.txt files.

You can update the package, don't delete the old one and let who won't update or won't use the old release to use it with 

```
pip install facebook-sdk==0.4.0
```

or 

```
facebook-sdk==0.4.0
```

in requiriments.txt

**Comment by martey** [comment]
> I really don't understand why you don't want to create a new package release.

I don't understand why you would think this, since I have said explicitly that 1.0.0 will be released when it's ready.

> Using the git source with pip is unreliable and totally broke the dependecy system: many deploy systems rely to requirements.txt files.

This is wrong. You can use pip, Git, and requirements files together: https://pip.pypa.io/en/latest/reference/pip_install/#git

> Please reopen this issue.

This isn't a bug with the library. If you want to discuss this further, create a new thread on the Google Group.
